In [1]:
import h5py

# Replace 'your_file.h5' with the path to your HDF5 file
file_path = '/media/patelm/T7/home/hiking_data/2024-06-25_seealpsee/seealpsee1.h5'

import numpy as np

In [19]:
# Open the HDF5 file
with h5py.File(file_path, 'r') as f:
    # List all groups
    print("Keys: %s" % f.keys())
    keys = list(f.keys())
    
    # Explore a specific dataset
    dataset = f[keys[2]]["elevation_map_raw"]
    print(f"Dataset Name: {keys[1]}")
    print(f"Dataset Keys: {dataset.keys()}")
    
    print(np.array(dataset["pose"][::50]))
# You can now analyze 'data' further using your preferred methods

Keys: <KeysViewHDF5 ['anymal_point_nav_ros', 'elevation_mapping', 'elevation_mapping_large', 'foot_scan', 'hdr_camera_front', 'lmm_nav_ros', 'lodia', 'open3d_slam', 'rtk_gps_driver', 'state_estimator', 'user_command_relay', 'wide_angle_camera_front']>
Dataset Name: elevation_mapping
Dataset Keys: <KeysViewHDF5 ['grid_map_data', 'layer_names', 'msg_t', 'msg_type', 'pose']>
[[[  1.           0.           0.          15.14999866]
  [  0.           1.           0.         -39.75000381]
  [  0.           0.           1.           0.        ]
  [  0.           0.           0.           1.        ]]

 [[  1.           0.           0.          18.1499958 ]
  [  0.           1.           0.         -40.65001297]
  [  0.           0.           1.           0.        ]
  [  0.           0.           0.           1.        ]]

 [[  1.           0.           0.          35.0999794 ]
  [  0.           1.           0.         -44.40005112]
  [  0.           0.           1.           0.        ]
  [  

In [4]:
file_path_merged = "/home/patelm/Data/nature_hiking/2024-06-25-seealpsee/h5_1_reind_gt_2/run1.h5py"

In [24]:
def get_time(hdf5_view, j=None):
    if j is None:
        return (
            np.array(hdf5_view["header_stamp_secs"])
            + np.array(hdf5_view["header_stamp_nsecs"]) * 10**-9
        )
    else:
        return (
            np.array(hdf5_view["header_stamp_secs"][j])
            + np.array(hdf5_view["header_stamp_nsecs"][j]) * 10**-9
        )


with h5py.File(file_path_merged, 'r') as f:
    # List all groups
    print("Keys: %s" % f.keys())
    keys = list(f.keys())
    dataset = f[keys[0]]
    travmap_key = "traversability_map_short_gt"
    print(dataset.keys())

    sample_idx = 288
    
    print(dataset[travmap_key].keys())
    print(get_time(dataset[travmap_key], j=sample_idx))  # This gives the timestamp 
    print(dataset[travmap_key]["position"][sample_idx]) # This is np array of size 3x1 (Same as the translation part of your HDF5 pose)
    print(dataset[travmap_key]["data"][sample_idx].shape) # This is the np array of shape (Layers , H, W)



Keys: <KeysViewHDF5 ['run1']>
<KeysViewHDF5 ['hdr_front', 'hdr_front-camera_info', 'lodia_path', 'traversability_map_micro', 'traversability_map_short', 'traversability_map_short_gt']>
<KeysViewHDF5 ['data', 'header_frame_id', 'header_seq', 'header_stamp_nsecs', 'header_stamp_secs', 'layers', 'length', 'orientation_xyzw', 'position', 'resolution', 'tf_rotation_xyzw', 'tf_translation']>
[1.71930417e+09]
[ 27.74998665 -42.15002823   0.        ]
(3, 375, 375)
